version: 2

build:
  os: ubuntu-22.04
  image: latest

python:
  version: "3.11"
  install:
    - method: pip
      path: .
    - requirements: requirements.txt

mkdocs:
  configuration: mkdocs.yml
  build:
    - method: mkdocs